services:
  backend:
    container_name: django
    build: . 
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./core:/app/
    environment:
      - SECRET_KEY=test
      - DEBUG=True
  smtp4dev:
    image: rnwood/smtp4dev:v3
    # restart: always
    ports:
      # Change the number before : to the port the web interface should be accessible on
      # Add 127.0.0.1: prefix for localhost-only access (recommended for security)
      - '5000:80'
      # Change the number before : to the port the SMTP server should be accessible on
      # Add 127.0.0.1: prefix for localhost-only access (recommended for security)
      - '25:25'
      # Change the number before : to the port the IMAP server should be accessible on
      # Add 127.0.0.1: prefix for localhost-only access (recommended for security)
      - '143:143'
      # Change the number before : to the port the POP3 server should be accessible on
      # Add 127.0.0.1: prefix for localhost-only access (recommended for security)
      - '110:110'
    volumes:
      # This is where smtp4dev stores the database..
        - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__Urls=http://*:80

      - ServerOptions__HostName=smtp4dev

  redis:
    container_name: redis-blog
    image: redis
    ports:
      - "6371:6379"
    command: redis-server --save 60 1 --loglevel warning

  worker: 
    build: .
    command: celery -A core worker --loglevel=info
    depends_on:
      - redis
      - backend
    volumes:
      - ./core:/app/
volumes:
  smtp4dev-data: